import 'package:flutter/material.dart';
import 'package:latlong2/latlong.dart';

/// A cluster of waypoints for organization and display optimization
@immutable
class WaypointCluster {
  const WaypointCluster({
    required this.id,
    required this.name,
    required this.waypointIds,
    required this.centerCoordinates,
    required this.radiusMeters,
    required this.createdAt,
    required this.userId,
    this.description,
    this.color,
    this.iconData,
    this.isAutoGenerated = false,
    this.clusterType = WaypointClusterType.manual,
    this.tags = const <String>[],
    this.metadata = const <String, dynamic>{},
    this.isActive = true,
    this.sortOrder = 0,
  });

  /// Create cluster from database map
  factory WaypointCluster.fromMap(Map<String, dynamic> map) => WaypointCluster(
        id: map['id'] as String,
        name: map['name'] as String,
        waypointIds: List<String>.from(map['waypoint_ids'] as List),
        centerCoordinates: LatLng(
          map['center_latitude'] as double,
          map['center_longitude'] as double,
        ),
        radiusMeters: map['radius_meters'] as double,
        createdAt:
            DateTime.fromMillisecondsSinceEpoch(map['created_at'] as int),
        userId: map['user_id'] as String,
        description: map['description'] as String?,
        color: map['color'] != null ? Color(map['color'] as int) : null,
        iconData: map['icon_code_point'] != null
            ? IconData(
                map['icon_code_point'] as int,
                fontFamily: map['icon_font_family'] as String?,
                fontPackage: map['icon_font_package'] as String?,
              )
            : null,
        isAutoGenerated: (map['is_auto_generated'] as int?) == 1,
        clusterType: WaypointClusterType.values.firstWhere(
          (type) => type.name == map['cluster_type'],
          orElse: () => WaypointClusterType.manual,
        ),
        tags: map['tags'] != null
            ? List<String>.from(map['tags'] as List)
            : const <String>[],
        metadata: map['metadata'] != null
            ? Map<String, dynamic>.from(map['metadata'] as Map)
            : const <String, dynamic>{},
        isActive: (map['is_active'] as int?) != 0,
        sortOrder: map['sort_order'] as int? ?? 0,
      );

  /// Unique identifier for this cluster
  final String id;

  /// Name of the cluster
  final String name;

  /// List of waypoint IDs in this cluster
  final List<String> waypointIds;

  /// Center coordinates of the cluster
  final LatLng centerCoordinates;

  /// Radius of the cluster in meters
  final double radiusMeters;

  /// When this cluster was created
  final DateTime createdAt;

  /// ID of the user who created this cluster
  final String userId;

  /// Optional description of the cluster
  final String? description;

  /// Optional color for the cluster
  final Color? color;

  /// Optional icon for the cluster
  final IconData? iconData;

  /// Whether this cluster was automatically generated
  final bool isAutoGenerated;

  /// Type of clustering algorithm used
  final WaypointClusterType clusterType;

  /// Tags for organizing clusters
  final List<String> tags;

  /// Additional metadata for the cluster
  final Map<String, dynamic> metadata;

  /// Whether this cluster is active/visible
  final bool isActive;

  /// Sort order for display
  final int sortOrder;

  /// Number of waypoints in this cluster
  int get waypointCount => waypointIds.length;

  /// Whether this cluster is empty
  bool get isEmpty => waypointIds.isEmpty;

  /// Whether this cluster has multiple waypoints
  bool get hasMultipleWaypoints => waypointIds.length > 1;

  /// Convert to map for database storage
  Map<String, dynamic> toMap() => <String, dynamic>{
        'id': id,
        'name': name,
        'waypoint_ids': waypointIds,
        'center_latitude': centerCoordinates.latitude,
        'center_longitude': centerCoordinates.longitude,
        'radius_meters': radiusMeters,
        'created_at': createdAt.millisecondsSinceEpoch,
        'user_id': userId,
        'description': description,
        'color': color?.toARGB32(),
        'icon_code_point': iconData?.codePoint,
        'icon_font_family': iconData?.fontFamily,
        'icon_font_package': iconData?.fontPackage,
        'is_auto_generated': isAutoGenerated ? 1 : 0,
        'cluster_type': clusterType.name,
        'tags': tags,
        'metadata': metadata,
        'is_active': isActive ? 1 : 0,
        'sort_order': sortOrder,
      };

  /// Create a copy with updated values
  WaypointCluster copyWith({
    String? id,
    String? name,
    List<String>? waypointIds,
    LatLng? centerCoordinates,
    double? radiusMeters,
    DateTime? createdAt,
    String? userId,
    String? description,
    Color? color,
    IconData? iconData,
    bool? isAutoGenerated,
    WaypointClusterType? clusterType,
    List<String>? tags,
    Map<String, dynamic>? metadata,
    bool? isActive,
    int? sortOrder,
  }) =>
      WaypointCluster(
        id: id ?? this.id,
        name: name ?? this.name,
        waypointIds: waypointIds ?? this.waypointIds,
        centerCoordinates: centerCoordinates ?? this.centerCoordinates,
        radiusMeters: radiusMeters ?? this.radiusMeters,
        createdAt: createdAt ?? this.createdAt,
        userId: userId ?? this.userId,
        description: description ?? this.description,
        color: color ?? this.color,
        iconData: iconData ?? this.iconData,
        isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
        clusterType: clusterType ?? this.clusterType,
        tags: tags ?? this.tags,
        metadata: metadata ?? this.metadata,
        isActive: isActive ?? this.isActive,
        sortOrder: sortOrder ?? this.sortOrder,
      );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WaypointCluster &&
          runtimeType == other.runtimeType &&
          id == other.id;

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() =>
      'WaypointCluster{id: $id, name: $name, waypointCount: $waypointCount}';
}

/// Types of waypoint clustering algorithms
enum WaypointClusterType {
  /// Manually created cluster
  manual,

  /// Distance-based clustering (DBSCAN-like)
  distance,

  /// Density-based clustering
  density,

  /// Grid-based clustering
  grid,

  /// Hierarchical clustering
  hierarchical,

  /// K-means clustering
  kmeans,

  /// Time-based clustering
  temporal,

  /// Activity-based clustering
  activity,

  /// Category-based clustering
  category,
}

/// Extension for waypoint cluster types
extension WaypointClusterTypeExtension on WaypointClusterType {
  /// Display name for the cluster type
  String get displayName {
    switch (this) {
      case WaypointClusterType.manual:
        return 'Manual';
      case WaypointClusterType.distance:
        return 'Distance-based';
      case WaypointClusterType.density:
        return 'Density-based';
      case WaypointClusterType.grid:
        return 'Grid-based';
      case WaypointClusterType.hierarchical:
        return 'Hierarchical';
      case WaypointClusterType.kmeans:
        return 'K-means';
      case WaypointClusterType.temporal:
        return 'Time-based';
      case WaypointClusterType.activity:
        return 'Activity-based';
      case WaypointClusterType.category:
        return 'Category-based';
    }
  }

  /// Whether this cluster type is automatically generated
  bool get isAutomatic {
    switch (this) {
      case WaypointClusterType.manual:
        return false;
      case WaypointClusterType.distance:
      case WaypointClusterType.density:
      case WaypointClusterType.grid:
      case WaypointClusterType.hierarchical:
      case WaypointClusterType.kmeans:
      case WaypointClusterType.temporal:
      case WaypointClusterType.activity:
      case WaypointClusterType.category:
        return true;
    }
  }
}

/// Configuration for automatic waypoint clustering
@immutable
class WaypointClusteringConfig {
  const WaypointClusteringConfig({
    this.enableAutoClustering = true,
    this.clusterType = WaypointClusterType.distance,
    this.maxDistance = 100.0,
    this.minPointsPerCluster = 2,
    this.maxClustersPerSession = 20,
    this.updateInterval = const Duration(minutes: 5),
    this.enableDynamicClustering = true,
    this.preserveManualClusters = true,
    this.clusterByCategory = false,
    this.clusterByTime = false,
    this.timeWindowHours = 24,
  });

  /// Whether to enable automatic clustering
  final bool enableAutoClustering;

  /// Default clustering algorithm to use
  final WaypointClusterType clusterType;

  /// Maximum distance between points in a cluster (meters)
  final double maxDistance;

  /// Minimum number of points required to form a cluster
  final int minPointsPerCluster;

  /// Maximum number of clusters per session
  final int maxClustersPerSession;

  /// How often to update automatic clusters
  final Duration updateInterval;

  /// Whether clusters should update dynamically as waypoints are added
  final bool enableDynamicClustering;

  /// Whether to preserve manually created clusters
  final bool preserveManualClusters;

  /// Whether to consider waypoint category when clustering
  final bool clusterByCategory;

  /// Whether to consider time when clustering
  final bool clusterByTime;

  /// Time window for temporal clustering (hours)
  final int timeWindowHours;

  /// Create a copy with updated values
  WaypointClusteringConfig copyWith({
    bool? enableAutoClustering,
    WaypointClusterType? clusterType,
    double? maxDistance,
    int? minPointsPerCluster,
    int? maxClustersPerSession,
    Duration? updateInterval,
    bool? enableDynamicClustering,
    bool? preserveManualClusters,
    bool? clusterByCategory,
    bool? clusterByTime,
    int? timeWindowHours,
  }) =>
      WaypointClusteringConfig(
        enableAutoClustering: enableAutoClustering ?? this.enableAutoClustering,
        clusterType: clusterType ?? this.clusterType,
        maxDistance: maxDistance ?? this.maxDistance,
        minPointsPerCluster: minPointsPerCluster ?? this.minPointsPerCluster,
        maxClustersPerSession:
            maxClustersPerSession ?? this.maxClustersPerSession,
        updateInterval: updateInterval ?? this.updateInterval,
        enableDynamicClustering:
            enableDynamicClustering ?? this.enableDynamicClustering,
        preserveManualClusters:
            preserveManualClusters ?? this.preserveManualClusters,
        clusterByCategory: clusterByCategory ?? this.clusterByCategory,
        clusterByTime: clusterByTime ?? this.clusterByTime,
        timeWindowHours: timeWindowHours ?? this.timeWindowHours,
      );

  @override
  String toString() =>
      'WaypointClusteringConfig{enabled: $enableAutoClustering, type: $clusterType, maxDistance: $maxDistance}';
}

/// Group of waypoints for organizational purposes
@immutable
class WaypointGroup {
  const WaypointGroup({
    required this.id,
    required this.name,
    required this.waypointIds,
    required this.createdAt,
    required this.userId,
    this.description,
    this.color,
    this.iconData,
    this.tags = const <String>[],
    this.isActive = true,
    this.sortOrder = 0,
    this.parentGroupId,
    this.groupType = WaypointGroupType.custom,
  });

  /// Create group from database map
  factory WaypointGroup.fromMap(Map<String, dynamic> map) => WaypointGroup(
        id: map['id'] as String,
        name: map['name'] as String,
        waypointIds: List<String>.from(map['waypoint_ids'] as List),
        createdAt:
            DateTime.fromMillisecondsSinceEpoch(map['created_at'] as int),
        userId: map['user_id'] as String,
        description: map['description'] as String?,
        color: map['color'] != null ? Color(map['color'] as int) : null,
        iconData: map['icon_code_point'] != null
            ? IconData(
                map['icon_code_point'] as int,
                fontFamily: map['icon_font_family'] as String?,
                fontPackage: map['icon_font_package'] as String?,
              )
            : null,
        tags: map['tags'] != null
            ? List<String>.from(map['tags'] as List)
            : const <String>[],
        isActive: (map['is_active'] as int?) != 0,
        sortOrder: map['sort_order'] as int? ?? 0,
        parentGroupId: map['parent_group_id'] as String?,
        groupType: WaypointGroupType.values.firstWhere(
          (type) => type.name == map['group_type'],
          orElse: () => WaypointGroupType.custom,
        ),
      );

  /// Unique identifier for this group
  final String id;

  /// Name of the group
  final String name;

  /// List of waypoint IDs in this group
  final List<String> waypointIds;

  /// When this group was created
  final DateTime createdAt;

  /// ID of the user who created this group
  final String userId;

  /// Optional description of the group
  final String? description;

  /// Optional color for the group
  final Color? color;

  /// Optional icon for the group
  final IconData? iconData;

  /// Tags for organizing groups
  final List<String> tags;

  /// Whether this group is active/visible
  final bool isActive;

  /// Sort order for display
  final int sortOrder;

  /// Parent group ID for hierarchical organization
  final String? parentGroupId;

  /// Type of group
  final WaypointGroupType groupType;

  /// Number of waypoints in this group
  int get waypointCount => waypointIds.length;

  /// Whether this group is empty
  bool get isEmpty => waypointIds.isEmpty;

  /// Whether this is a root-level group
  bool get isRootGroup => parentGroupId == null;

  /// Convert to map for database storage
  Map<String, dynamic> toMap() => <String, dynamic>{
        'id': id,
        'name': name,
        'waypoint_ids': waypointIds,
        'created_at': createdAt.millisecondsSinceEpoch,
        'user_id': userId,
        'description': description,
        'color': color?.toARGB32(),
        'icon_code_point': iconData?.codePoint,
        'icon_font_family': iconData?.fontFamily,
        'icon_font_package': iconData?.fontPackage,
        'tags': tags,
        'is_active': isActive ? 1 : 0,
        'sort_order': sortOrder,
        'parent_group_id': parentGroupId,
        'group_type': groupType.name,
      };

  /// Create a copy with updated values
  WaypointGroup copyWith({
    String? id,
    String? name,
    List<String>? waypointIds,
    DateTime? createdAt,
    String? userId,
    String? description,
    Color? color,
    IconData? iconData,
    List<String>? tags,
    bool? isActive,
    int? sortOrder,
    String? parentGroupId,
    WaypointGroupType? groupType,
  }) =>
      WaypointGroup(
        id: id ?? this.id,
        name: name ?? this.name,
        waypointIds: waypointIds ?? this.waypointIds,
        createdAt: createdAt ?? this.createdAt,
        userId: userId ?? this.userId,
        description: description ?? this.description,
        color: color ?? this.color,
        iconData: iconData ?? this.iconData,
        tags: tags ?? this.tags,
        isActive: isActive ?? this.isActive,
        sortOrder: sortOrder ?? this.sortOrder,
        parentGroupId: parentGroupId ?? this.parentGroupId,
        groupType: groupType ?? this.groupType,
      );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WaypointGroup &&
          runtimeType == other.runtimeType &&
          id == other.id;

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() =>
      'WaypointGroup{id: $id, name: $name, waypointCount: $waypointCount}';
}

/// Types of waypoint groups
enum WaypointGroupType {
  /// Custom user-created group
  custom,

  /// Favorites group
  favorites,

  /// Recently visited group
  recent,

  /// Planned waypoints group
  planned,

  /// Completed waypoints group
  completed,

  /// Shared waypoints group
  shared,

  /// Imported waypoints group
  imported,

  /// Route waypoints group
  route,

  /// Emergency waypoints group
  emergency,
}

/// Extension for waypoint group types
extension WaypointGroupTypeExtension on WaypointGroupType {
  /// Display name for the group type
  String get displayName {
    switch (this) {
      case WaypointGroupType.custom:
        return 'Custom';
      case WaypointGroupType.favorites:
        return 'Favorites';
      case WaypointGroupType.recent:
        return 'Recent';
      case WaypointGroupType.planned:
        return 'Planned';
      case WaypointGroupType.completed:
        return 'Completed';
      case WaypointGroupType.shared:
        return 'Shared';
      case WaypointGroupType.imported:
        return 'Imported';
      case WaypointGroupType.route:
        return 'Route';
      case WaypointGroupType.emergency:
        return 'Emergency';
    }
  }

  /// Whether this group type is system-managed
  bool get isSystemGroup {
    switch (this) {
      case WaypointGroupType.recent:
      case WaypointGroupType.completed:
      case WaypointGroupType.imported:
        return true;
      case WaypointGroupType.custom:
      case WaypointGroupType.favorites:
      case WaypointGroupType.planned:
      case WaypointGroupType.shared:
      case WaypointGroupType.route:
      case WaypointGroupType.emergency:
        return false;
    }
  }

  /// Default icon for this group type
  IconData get defaultIcon {
    switch (this) {
      case WaypointGroupType.custom:
        return Icons.folder;
      case WaypointGroupType.favorites:
        return Icons.favorite;
      case WaypointGroupType.recent:
        return Icons.history;
      case WaypointGroupType.planned:
        return Icons.schedule;
      case WaypointGroupType.completed:
        return Icons.check_circle;
      case WaypointGroupType.shared:
        return Icons.share;
      case WaypointGroupType.imported:
        return Icons.download;
      case WaypointGroupType.route:
        return Icons.route;
      case WaypointGroupType.emergency:
        return Icons.emergency;
    }
  }
}
